{
    "openapi": "3.0.1",
    "info": {
        "title": "Emails",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "You send and manage emails to your customers using a third-party email provider, and you want to programmatically log your email data to the associated records in your HubSpot account.",
        "x-hubspot-related-documentation": [
            {
                "name": "Emails Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/engagements/email"
            }
        ],
        "x-hubspot-introduction": "Use the email engagements API to associate emails with records in your CRM. You can include various metadata fields as needed, including the email's headers, subject line, and body."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com/crm/v3/objects/emails"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/batch/read": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Read a batch of emails by internal ID, or unique property values",
                "description": "Read a batch of Objects identified by internal ID, or optionally any unique property value as specified by the `idProperty` query param. Control what is returned via the `properties` query param.",
                "operationId": "post-/crm/v3/objects/emails/batch/read_read",
                "security": [
                    {
                        "oauth2_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ]
            }
        },
        "/{emailId}": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Read an Object identified by `{emailId}`. `{emailId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
                "description": "Read an Object identified by `{emailId}`. `{emailId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/emails/{emailId}_getById",
                "security": [
                    {
                        "oauth2_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Basic"
                ],
                "summary": "Move an email to the recycling bin.",
                "description": "Move an Object identified by `{emailId}` to the recycling bin.",
                "operationId": "delete-/crm/v3/objects/emails/{emailId}_archive",
                "security": [
                    {
                        "oauth2_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Basic"
                ],
                "summary": "Partially update an email by ID.",
                "description": "Perform a partial update of an Object identified by `{emailId}`. `{emailId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
                "operationId": "patch-/crm/v3/objects/emails/{emailId}_update",
                "security": [
                    {
                        "oauth2_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/archive": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Archive a batch of emails by ID.",
                "description": "Archive a batch of Objects identified by internal ID.",
                "operationId": "post-/crm/v3/objects/emails/batch/archive_archive",
                "security": [
                    {
                        "oauth2_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/create": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Create a batch of emails.",
                "description": "Create a batch of Objects with the given properties and return a copy of the objects, including the IDs.",
                "operationId": "post-/crm/v3/objects/emails/batch/create_create",
                "security": [
                    {
                        "oauth2_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/update": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Update a batch of emails by ID.",
                "description": "Update a batch of Objects identified by internal ID.",
                "operationId": "post-/crm/v3/objects/emails/batch/update_update",
                "security": [
                    {
                        "oauth2_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Retrieve a page of emails.",
                "description": "Read a page of emails. Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/emails_getPage",
                "security": [
                    {
                        "oauth2_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Basic"
                ],
                "summary": "Create a new email object.",
                "description": "Create a email with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard emails is provided.",
                "operationId": "post-/crm/v3/objects/emails_create",
                "security": [
                    {
                        "oauth2_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/upsert": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Upsert a batch of emails.",
                "description": "Create or update a batch of Objects identified by unique property values. If an object with a matching unique property value exists, it will be updated. Otherwise, a new object will be created.",
                "operationId": "post-/crm/v3/objects/emails/batch/upsert_upsert",
                "security": [
                    {
                        "oauth2_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/search": {
            "post": {
                "tags": [
                    "Search"
                ],
                "summary": "Search for emails by filter.",
                "description": "Search for emails in your HubSpot account. Use the `filterGroups` parameter to specify the properties and values to filter for.",
                "operationId": "post-/crm/v3/objects/emails/search_doSearch",
                "security": [
                    {
                        "oauth2_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "sales-email-read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "e-commerce": "e-commerce",
                            "crm.objects.custom.write": "Change custom object records",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.goals.read": "Read goals",
                            "tickets": "Read and write tickets",
                            "crm.objects.custom.read": "View custom object records",
                            "sales-email-read": ""
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.contacts.read": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.companies.read": " ",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.deals.read": " ",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.deals.write": " ",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.companies.write": " ",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.orders.read": "Read Orders"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header",
                "x-ballerina-name": "privateAppLegacy"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header",
                "x-ballerina-name": "privateApp"
            }
        }
    },
    "x-hubspot-available-client-libraries": [
        "PHP",
        "Node",
        "Ruby",
        "Python"
    ],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE"
    },
    "x-hubspot-documentation-banner": "NONE"
}