// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# Standard error response object returned when an API request fails.
public type StandardError record {
    # Optional sub-category providing additional error classification.
    record {} subCategory?;
    # Contextual metadata map with string array values for the error.
    record {|string[]...;|} context;
    # Map of relevant links associated with the error response.
    record {|string...;|} links;
    # Unique identifier for the error instance.
    string id?;
    # High-level category classifying the type of error.
    string category;
    # Human-readable description of the error.
    string message;
    # List of detailed error objects describing individual failures.
    ErrorDetail[] errors;
    # HTTP status string associated with the error response.
    string status;
};

# Paginated collection of associated object IDs returned in a response.
public type CollectionResponseAssociatedId record {
    # Pagination metadata containing cursors for navigating to the next or previous page.
    Paging paging?;
    # Array of associated ID objects returned in the response.
    AssociatedId[] results;
};

# Represents the Queries record for the operation: post-/crm/v3/objects/emails/batch/read_read
public type PostCrmV3ObjectsEmailsBatchReadReadQueries record {
    # Whether to return only results that have been archived
    boolean archived = false;
};

# Defines association targets and relationship types for an object.
public type PublicAssociationsForObject record {
    # List of association type specifications for the relationship.
    AssociationSpec[] types;
    # Represents a public object identifier containing a unique ID string.
    PublicObjectId to;
};

# Batch operation response containing results and processing status.
public type BatchResponseSimplePublicObject record {
    # Datetime when the batch operation completed.
    string completedAt;
    # Datetime when the batch operation was requested.
    string requestedAt?;
    # Datetime when the batch operation began processing.
    string startedAt;
    # Map of relevant links related to the batch response.
    record {|string...;|} links?;
    # Array of email objects returned by the batch operation.
    SimplePublicObject[] results;
    # Current status of the batch operation.
    "PENDING"|"PROCESSING"|"CANCELED"|"COMPLETE" status;
};

# A group of filters combined to refine search query results.
public type FilterGroup record {
    # Array of filter conditions applied within the group.
    Filter[] filters;
};

# Detailed information about a specific error encountered in a request.
public type ErrorDetail record {
    # A specific category that contains more specific detail about the error
    string subCategory?;
    # The status code associated with the error detail
    string code?;
    # The name of the field or parameter in which the error was found
    string 'in?;
    # Context about the error condition
    record {|string[]...;|} context?;
    # A human readable message describing the error along with remediation steps where appropriate
    string message;
};

# Pagination metadata for forward-only cursor-based navigation.
public type ForwardPaging record {
    NextPage next?;
};

# A minimal object representation containing only a unique identifier.
public type SimplePublicObjectId record {
    # The unique identifier of the object.
    string id;
};

# Batch upsert response containing results, errors, and operation status details.
public type BatchResponseSimplePublicUpsertObjectWithErrors record {
    # Timestamp when the batch operation completed.
    string completedAt;
    # Total number of errors encountered during the batch operation.
    int:Signed32 numErrors?;
    # Timestamp when the batch operation was requested.
    string requestedAt?;
    # Timestamp when the batch operation began processing.
    string startedAt;
    # Map of relevant links associated with the batch response.
    record {|string...;|} links?;
    # Array of successfully upserted email objects from the batch.
    SimplePublicUpsertObject[] results;
    # Array of errors encountered for individual records in the batch.
    StandardError[] errors?;
    # Current status of the batch upsert operation.
    "PENDING"|"PROCESSING"|"CANCELED"|"COMPLETE" status;
};

# Input schema for batch reading email objects by their IDs.
public type BatchReadInputSimplePublicObjectId record {
    # List of properties to return along with their historical values.
    string[] propertiesWithHistory;
    # The property name used as the unique identifier for batch lookup.
    string idProperty?;
    # Array of object IDs to retrieve in the batch read operation.
    SimplePublicObjectId[] inputs;
    # List of property names to include in the response for each object.
    string[] properties;
};

# Response object containing batch upsert results, status, and execution timestamps.
public type BatchResponseSimplePublicUpsertObject record {
    # Datetime when the batch upsert operation completed.
    string completedAt;
    # Datetime when the batch upsert operation was requested.
    string requestedAt?;
    # Datetime when the batch upsert operation started processing.
    string startedAt;
    # Map of related resource links associated with the batch response.
    record {|string...;|} links?;
    # Array of upserted email objects returned from the batch operation.
    SimplePublicUpsertObject[] results;
    # Current processing status of the batch operation.
    "PENDING"|"PROCESSING"|"CANCELED"|"COMPLETE" status;
};

# A property value paired with its source metadata and recorded timestamp.
public type ValueWithTimestamp record {
    # Identifier of the source that provided the value.
    string sourceId?;
    # The type of source that set or updated the value.
    string sourceType;
    # Human-readable label describing the value's source.
    string sourceLabel?;
    # ID of the user who last updated the value.
    int:Signed32 updatedByUserId?;
    # The actual property value recorded at the given timestamp.
    string value;
    # Datetime when the value was recorded or last updated.
    string timestamp;
};

# Input schema containing a list of object IDs for a batch operation.
public type BatchInputSimplePublicObjectId record {
    # Array of object IDs to process in the batch request.
    SimplePublicObjectId[] inputs;
};

# Represents the Queries record for the operation: patch-/crm/v3/objects/emails/{emailId}_update
public type PatchCrmV3ObjectsEmailsEmailIdUpdateQueries record {
    # The name of a property whose values are unique for this object type
    string idProperty?;
};

# OAuth2 Refresh Token Grant Configs
public type OAuth2RefreshTokenGrantConfig record {|
    *http:OAuth2RefreshTokenGrantConfig;
    # Refresh URL
    string refreshUrl = "https://api.hubapi.com/oauth/v1/token";
|};

# Input schema containing a list of objects to create or update in batch.
public type BatchInputSimplePublicObjectBatchInputUpsert record {
    # Array of email objects to upsert in the batch operation.
    SimplePublicObjectBatchInputUpsert[] inputs;
};

# A paginated collection of email objects with a total count and forward paging cursor.
public type CollectionResponseWithTotalSimplePublicObjectForwardPaging record {
    # Total number of email records matching the request.
    int:Signed32 total;
    # Pagination metadata for forward-only cursor-based navigation.
    ForwardPaging paging?;
    # Array of email objects returned in the current page.
    SimplePublicObject[] results;
};

# Represents a single email object with its properties, timestamps, and archival status.
public type SimplePublicObject record {
    # Timestamp when the email record was created.
    string createdAt;
    # Indicates whether the email record is archived.
    boolean archived?;
    # Timestamp when the email record was archived.
    string archivedAt?;
    # Map of email properties to their historical values with timestamps.
    record {|ValueWithTimestamp[]...;|} propertiesWithHistory?;
    # Unique identifier of the email record.
    string id;
    # Key-value map of email properties and their current values.
    record {|string?...;|} properties;
    # Timestamp when the email record was last updated.
    string updatedAt;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Provides Auth configurations needed when communicating with a remote HTTP endpoint.
    http:BearerTokenConfig|OAuth2RefreshTokenGrantConfig|ApiKeysConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Represents a public object identifier containing a unique ID string.
public type PublicObjectId record {
    # Unique identifier of the public object.
    string id;
};

# Pagination metadata containing cursors for navigating to the next or previous page.
public type Paging record {
    NextPage next?;
    # Pagination cursor details for navigating to the previous page of results.
    PreviousPage prev?;
};

# Request payload for searching email objects with filters, sorting, and pagination.
public type PublicObjectSearchRequest record {
    # Full-text search query string to filter email results.
    string query?;
    # Maximum number of results to return per page.
    int:Signed32 'limit?;
    # Cursor token for retrieving the next page of results.
    string after?;
    # List of property names to sort results by.
    string[] sorts?;
    # List of property names to include in the response.
    string[] properties?;
    # Groups of filters used to narrow search results.
    FilterGroup[] filterGroups?;
};

# Input payload for upserting a single email object in a batch operation, including its ID and properties.
public type SimplePublicObjectBatchInputUpsert record {
    # The property name used as the unique identifier for the upsert.
    string idProperty?;
    # Trace ID for tracking the object write operation.
    string objectWriteTraceId?;
    # The unique identifier of the email object to upsert.
    string id;
    # Key-value map of email properties to create or update.
    record {|string...;|} properties;
};

# Batch operation response containing email results, processing status, timestamps, and any errors encountered.
public type BatchResponseSimplePublicObjectWithErrors record {
    # Timestamp indicating when the batch operation completed.
    string completedAt;
    # Total number of errors encountered during the batch operation.
    int:Signed32 numErrors?;
    # Timestamp indicating when the batch operation was requested.
    string requestedAt?;
    # Timestamp indicating when the batch operation started processing.
    string startedAt;
    # Map of related link names to their associated URLs.
    record {|string...;|} links?;
    # List of successfully processed email objects from the batch.
    SimplePublicObject[] results;
    # List of errors encountered for individual records in the batch.
    StandardError[] errors?;
    # Current processing status of the batch operation.
    "PENDING"|"PROCESSING"|"CANCELED"|"COMPLETE" status;
};

# Request body schema for creating or updating an email object with its properties.
public type SimplePublicObjectInput record {
    # Trace identifier for auditing the write operation on this object.
    string objectWriteTraceId?;
    # Key-value map of email property names and their corresponding values.
    record {|string...;|} properties;
};

# Represents the Queries record for the operation: get-/crm/v3/objects/emails/{emailId}_getById
public type GetCrmV3ObjectsEmailsEmailIdGetByIdQueries record {
    # A comma separated list of object types to retrieve associated IDs for. If any of the specified associations do not exist, they will be ignored
    string[] associations?;
    # Whether to return only results that have been archived
    boolean archived = false;
    # A comma separated list of the properties to be returned along with their history of previous values. If any of the specified properties are not present on the requested object(s), they will be ignored
    string[] propertiesWithHistory?;
    # The name of a property whose values are unique for this object type
    string idProperty?;
    # A comma separated list of the properties to be returned in the response. If any of the specified properties are not present on the requested object(s), they will be ignored
    string[] properties?;
};

# Paginated collection of email objects, each including their associated records.
public type CollectionResponseSimplePublicObjectWithAssociationsForwardPaging record {
    # Pagination metadata for forward-only cursor-based navigation.
    ForwardPaging paging?;
    # Array of email objects returned in the current page of results.
    SimplePublicObjectWithAssociations[] results;
};

# Defines the category and type of an association between two CRM objects.
public type AssociationSpec record {
    # Category of the association: HUBSPOT_DEFINED, USER_DEFINED, or INTEGRATOR_DEFINED.
    "HUBSPOT_DEFINED"|"USER_DEFINED"|"INTEGRATOR_DEFINED" associationCategory;
    # Numeric identifier specifying the type of association.
    int:Signed32 associationTypeId;
};

# Represents an email object with its properties, metadata, and associated CRM records.
public type SimplePublicObjectWithAssociations record {
    # Map of associated CRM objects grouped by association type.
    record {|CollectionResponseAssociatedId...;|} associations?;
    # Timestamp indicating when the email record was created.
    string createdAt;
    # Indicates whether the email record has been archived.
    boolean archived?;
    # Timestamp indicating when the email record was archived.
    string archivedAt?;
    # Map of property names to their historical values with timestamps.
    record {|ValueWithTimestamp[]...;|} propertiesWithHistory?;
    # Unique identifier of the email record.
    string id;
    # Key-value map of the email record's current property values.
    record {|string?...;|} properties;
    # Timestamp indicating when the email record was last modified.
    string updatedAt;
};

# Defines a filter condition used to query CRM objects by property and operator.
public type Filter record {
    # Upper bound value used with the BETWEEN operator for range filtering.
    string highValue?;
    # The name of the email property to filter on.
    string propertyName;
    # A list of values to match against for the filter.
    string[] values?;
    # A single value to match against for the filter.
    string value?;
    # The comparison operator used to evaluate the filter condition.
    "EQ"|"NEQ"|"LT"|"LTE"|"GT"|"GTE"|"BETWEEN"|"IN"|"NOT_IN"|"HAS_PROPERTY"|"NOT_HAS_PROPERTY"|"CONTAINS_TOKEN"|"NOT_CONTAINS_TOKEN" operator;
};

# Pagination cursor details for navigating to the previous page of results.
public type PreviousPage record {
    # The cursor token representing the start of the previous page.
    string before;
    # A direct URL link to the previous page of results.
    string link?;
};

# Request body containing a batch of email objects to create.
public type BatchInputSimplePublicObjectInputForCreate record {
    # An array of email objects to be created in batch.
    SimplePublicObjectInputForCreate[] inputs;
};

# Request body containing a batch of email objects to update.
public type BatchInputSimplePublicObjectBatchInput record {
    # An array of email objects to be updated in batch.
    SimplePublicObjectBatchInput[] inputs;
};

# Represents an email object returned after an upsert operation, indicating whether it was newly created.
public type SimplePublicUpsertObject record {
    # The timestamp when the email object was created.
    string createdAt;
    # Indicates whether the email object is archived.
    boolean archived?;
    # The timestamp when the email object was archived.
    string archivedAt?;
    # Indicates whether the object was newly created by the upsert.
    boolean 'new;
    # A map of property values including their historical change records.
    record {|ValueWithTimestamp[]...;|} propertiesWithHistory?;
    # The unique identifier of the email object.
    string id;
    # A map of the email object's property names to their current values.
    record {|string...;|} properties;
    # The timestamp when the email object was last updated.
    string updatedAt;
};

public type SimplePublicObjectBatchInput record {
    string idProperty?;
    string objectWriteTraceId?;
    string id;
    record {|string...;|} properties;
};

# Represents the Queries record for the operation: get-/crm/v3/objects/emails_getPage
public type GetCrmV3ObjectsEmailsGetPageQueries record {
    # A comma separated list of object types to retrieve associated IDs for. If any of the specified associations do not exist, they will be ignored
    string[] associations?;
    # Whether to return only results that have been archived
    boolean archived = false;
    # A comma separated list of the properties to be returned along with their history of previous values. If any of the specified properties are not present on the requested object(s), they will be ignored. Usage of this parameter will reduce the maximum number of objects that can be read by a single request
    string[] propertiesWithHistory?;
    # The maximum number of results to display per page
    int:Signed32 'limit = 10;
    # The paging cursor token of the last successfully read resource will be returned as the `paging.next.after` JSON property of a paged response containing more results
    string after?;
    # A comma separated list of the properties to be returned in the response. If any of the specified properties are not present on the requested object(s), they will be ignored
    string[] properties?;
};

public type NextPage record {
    string link?;
    string after;
};

public type AssociatedId record {
    string id;
    string 'type;
};

# Provides API key configurations needed when communicating with a remote HTTP endpoint.
public type ApiKeysConfig record {|
    string privateAppLegacy;
    string privateApp;
|};

public type SimplePublicObjectInputForCreate record {
    PublicAssociationsForObject[] associations;
    string objectWriteTraceId?;
    record {|string...;|} properties;
};
